name: Automerge

on: 
 pull_request:
  types: 
   - closed

jobs:
 automerge:
  runs-on: ubuntu-latest

  steps:

   - name: Checkout code
     uses: actions/checkout@v2

   - name: Automerge
     run: |
      if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.base.ref }}" == "main" ]; then
        git config --global user.email "action@github.com"
        git config --global user.name "Github Actions"
        git fetch
        git checkout main

        # Create an empty commit to establish a common ancestor
        git commit --allow-empty -m "Create empty commit for merge"

        git fetch origin "${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}"
        git merge --ff-only "origin/${{ github.event.pull_request.head.ref }}"
        git push
      fi  
